export const targetSentenceToRoute = new Map<string, [string, string, string[]]>([
  ["get the filesystem file ''", ["get", "/:userId/class/:classId/filesystem/:itemName", []]],
  ["post the filesystem file ''", ["post", "", []]],
  ["get the filesystem folder ''", ["get", "/:userId/class/:classId/filesystem/:itemName", []]],
  ["post the filesystem folder ''", ["post", "", []]],
  ["get the assignment '' information", ["get", "/:userId/class/:classId/assignment/:assignmentId", []]],
  ["get the assignment '' due date", ["get", "/:userId/class/:classId/assignment/:assignmentId", ['dueDate']]],
  ["get the assignment '' files", ["get", "/:userId/class/:classId/assignment/:assignmentId", ['files']]],
  ["get all the assignment '' student submission", ["get", "/:userId/class/:classId/assignment/:assignmentId", []]],
  ["get the assignment '' submission file from student ''", ["get", "", []]],
  ["get the assignment '' submission status from student ''", ["get", "", []]],
  ["put the assignment ''", ["put", "/:userId/class/:classId/assignment/:assignmentId/submit", []]],
  ["post the annoucement ''", ["post", "", []]],
  ["get the recent annoucement ''", ["get", "", []]],
])